### ISSUE TITLE
Graylog stops processing messages after a few hours

### ISSUE THREAD

**Issue by jasonhillier** [Graylog2/graylog2-images#130]
I've broken this down into the least number of steps necessary to reproduce:

Have tried graylog2/allinone and graylog2/allinone-beta docker images
Using defaults, not even changing the config, launching with: docker run -d -p 80:9000 -p 12201:12201 -p 12201:12201/udp graylog2/allinone-beta

After logging in, the only changes I make are:
*Add a GELF TCP input
*Add a JSON formatter to this input

I have two collector daemons running on remote machines publishing messages. Avg <10msg/sec. It processes messages fine for a few hours, using little CPU. But after awhile...

Running on AWS instance m3.large Ubuntu 14.04
top output shows:
top - 21:19:03 up 8 days, 20:48,  1 user,  load average: 5.23, 5.24, 5.15
Tasks: 163 total,   1 running, 162 sleeping,   0 stopped,   0 zombie
%Cpu(s): 99.7 us,  0.3 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   7659540 total,  4342964 used,  3316576 free,   158356 buffers
KiB Swap:        0 total,        0 used,        0 free.  1761036 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                         
 2361 ubuntu    20   0 4276924 1.062g  19100 S 196.8 14.5 331:33.15 java                                                                                                            
 2407 ubuntu    20   0 3480444 532868  16500 S   1.3  7.0   1:15.59 java                                                                                                            
 2060 ubuntu    20   0  465016  80424  44260 S   0.7  1.0   1:14.19 mongod                                                                                                          
 1976 ubuntu    20   0   20160  11408   4440 S   0.3  0.1   0:13.82 etcd                                                                                                            
    1 root      20   0   33480   2148    780 S   0.0  0.0   0:01.64 init                                                                                                            
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.03 kthre

It seems that a java process keeps getting railed, not sure why, process logs not showing anything significant as far as I can tell.

I've also tried installing the graylog packages directly (not using docker) and following these steps reproduces the problem every time.

**Comment by moricard** [comment]
Same problem here it was working fine until it completely stopped processing messages. Restarting does not help.

**Comment by mariussturm** [comment]
Could you please append logs of the Graylog-server and Elasticsearch processes here? You can find them in /var/log/graylog/[server|elasticsearch]/current

**Comment by moricard** [comment]
I do have some OOM errors in the Graylog-server:

```
    2016-05-11_15:24:43.95385 ERROR [ServiceManager] Service JournalReader [FAILED] has failed in the RUNNING state.
2016-05-11_15:24:43.95387 java.lang.OutOfMemoryError: Java heap space
2016-05-11_15:24:43.95514       at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
2016-05-11_15:24:43.95814       at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
2016-05-11_15:24:43.95879       at kafka.log.FileMessageSet$$anon$1.makeNext(FileMessageSet.scala:188)
2016-05-11_15:24:43.95974       at kafka.log.FileMessageSet$$anon$1.makeNext(FileMessageSet.scala:165)
2016-05-11_15:24:43.96039       at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:66)
2016-05-11_15:24:43.96235       at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:58)
2016-05-11_15:24:43.96273       at org.graylog2.shared.journal.KafkaJournal.read(KafkaJournal.java:470)
2016-05-11_15:24:43.96373       at org.graylog2.shared.journal.KafkaJournal.read(KafkaJournal.java:435)
2016-05-11_15:24:43.96405       at org.graylog2.shared.journal.JournalReader.run(JournalReader.java:136)
2016-05-11_15:24:43.96477       at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
2016-05-11_15:24:43.96536       at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
2016-05-11_15:24:43.96599       at java.lang.Thread.run(Thread.java:745)
2016-05-11_15:24:43.96666 INFO  [InputStateListener] Input [GELF UDP/571f85d1e4b01de42542d245] is now RUNNING
2016-05-11_15:24:43.96711 Exception in thread "JournalReader" java.lang.OutOfMemoryError: Java heap space
2016-05-11_15:24:43.96776       at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
2016-05-11_15:24:43.96871       at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
2016-05-11_15:24:43.96951       at kafka.log.FileMessageSet$$anon$1.makeNext(FileMessageSet.scala:188)
2016-05-11_15:24:43.97013       at kafka.log.FileMessageSet$$anon$1.makeNext(FileMessageSet.scala:165)
2016-05-11_15:24:43.97120       at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:66)
2016-05-11_15:24:43.97121       at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:58)
2016-05-11_15:24:43.97173       at org.graylog2.shared.journal.KafkaJournal.read(KafkaJournal.java:470)
2016-05-11_15:24:43.97237       at org.graylog2.shared.journal.KafkaJournal.read(KafkaJournal.java:435)
2016-05-11_15:24:43.97293       at org.graylog2.shared.journal.JournalReader.run(JournalReader.java:136)
2016-05-11_15:24:43.97335       at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
2016-05-11_15:24:43.97405       at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
2016-05-11_15:24:43.97728       at java.lang.Thread.run(Thread.java:745)
...skipping...
2016-05-11_15:24:43.95814       at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
2016-05-11_15:24:43.95879       at kafka.log.FileMessageSet$$anon$1.makeNext(FileMessageSet.scala:188)
2016-05-11_15:24:43.95974       at kafka.log.FileMessageSet$$anon$1.makeNext(FileMessageSet.scala:165)
2016-05-11_15:24:43.96039       at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:66)
2016-05-11_15:24:43.96235       at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:58)
2016-05-11_15:24:43.96273       at org.graylog2.shared.journal.KafkaJournal.read(KafkaJournal.java:470)
2016-05-11_15:24:43.96373       at org.graylog2.shared.journal.KafkaJournal.read(KafkaJournal.java:435)
2016-05-11_15:24:43.96405       at org.graylog2.shared.journal.JournalReader.run(JournalReader.java:136)
2016-05-11_15:24:43.96477       at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
2016-05-11_15:24:43.96536       at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
2016-05-11_15:24:43.96599       at java.lang.Thread.run(Thread.java:745)
2016-05-11_15:24:43.96666 INFO  [InputStateListener] Input [GELF UDP/571f85d1e4b01de42542d245] is now RUNNING
2016-05-11_15:24:43.96711 Exception in thread "JournalReader" java.lang.OutOfMemoryError: Java heap space
2016-05-11_15:24:43.96776       at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
2016-05-11_15:24:43.96871       at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
2016-05-11_15:24:43.96951       at kafka.log.FileMessageSet$$anon$1.makeNext(FileMessageSet.scala:188)
2016-05-11_15:24:43.97013       at kafka.log.FileMessageSet$$anon$1.makeNext(FileMessageSet.scala:165)
2016-05-11_15:24:43.97120       at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:66)
2016-05-11_15:24:43.97121       at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:58)
2016-05-11_15:24:43.97173       at org.graylog2.shared.journal.KafkaJournal.read(KafkaJournal.java:470)
2016-05-11_15:24:43.97237       at org.graylog2.shared.journal.KafkaJournal.read(KafkaJournal.java:435)
2016-05-11_15:24:43.97293       at org.graylog2.shared.journal.JournalReader.run(JournalReader.java:136)
2016-05-11_15:24:43.97335       at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
2016-05-11_15:24:43.97405       at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
2016-05-11_15:24:43.97728       at java.lang.Thread.run(Thread.java:745)
2016-05-11_15:24:43.97781 WARN  [NettyTransport] receiveBufferSize (SO_RCVBUF) for input SyslogUDPInput{title=docker-containers-syslog-udp, type=org.graylog2.inputs.syslog.udp.SyslogUDPInput, nodeId=47c30bd8-0b23-11e6-b512-3e1d05defe78} should be 262144 but is 212992.
2016-05-11_15:24:43.97846 INFO  [InputStateListener] Input [Syslog UDP/57328340e4b0f020a3e6158a] is now RUNNING
2016-05-11_15:24:43.97943 WARN  [NettyTransport] receiveBufferSize (SO_RCVBUF) for input GELFUDPInput{title=appliance-gelf-udp, type=org.graylog2.inputs.gelf.udp.GELFUDPInput, nodeId=47c30bd8-0b23-11e6-b512-3e1d05defe78} should be 1048576 but is 212992.
2016-05-11_15:24:43.97999 INFO  [InputStateListener] Input [GELF UDP/571f83cae4b05dba7d1545ce] is now RUNNING
2016-05-11_15:24:44.54034 INFO  [AbstractValidatingSessionManager] Enabling session validation scheduler...
2016-05-11_15:26:19.32477 INFO  [SystemProcessingResource] Resumed message processing - triggered by REST call.
```

elastic:

```
    ...skipping...
2016-05-11_15:03:32.15154 [2016-05-11 11:03:32,149][INFO ][transport                ] [Blacklash] bound_address {inet[/127.0.0.1:9300]}, publish_address {inet
[/127.0.0.1:9300]}
2016-05-11_15:03:32.17335 [2016-05-11 11:03:32,172][INFO ][discovery                ] [Blacklash] graylog2/iALS60EbRTiRyE_4K-nWpg
2016-05-11_15:03:42.21367 [2016-05-11 11:03:42,213][INFO ][cluster.service          ] [Blacklash] new_master [Blacklash][iALS60EbRTiRyE_4K-nWpg][cddbff078b64]
[inet[/127.0.0.1:9300]], reason: zen-disco-join (elected_as_master)
2016-05-11_15:03:42.38498 [2016-05-11 11:03:42,383][INFO ][http                     ] [Blacklash] bound_address {inet[/127.0.0.1:9200]}, publish_address {inet
[/127.0.0.1:9200]}
2016-05-11_15:03:42.38499 [2016-05-11 11:03:42,383][INFO ][node                     ] [Blacklash] started
2016-05-11_15:03:42.47540 [2016-05-11 11:03:42,474][INFO ][gateway                  ] [Blacklash] recovered [16] indices into cluster_state
2016-05-11_15:03:47.03921 [2016-05-11 11:03:47,037][INFO ][node                     ] [Blacklash] stopping ...
2016-05-11_15:03:47.29330 [2016-05-11 11:03:47,290][INFO ][node                     ] [Blacklash] stopped
2016-05-11_15:03:47.29331 [2016-05-11 11:03:47,290][INFO ][node                     ] [Blacklash] closing ...
2016-05-11_15:03:47.30312 [2016-05-11 11:03:47,302][INFO ][node                     ] [Blacklash] closed
2016-05-11_15:03:47.63306 ./run: 6: ulimit: error setting limit (Operation not permitted)
2016-05-11_15:03:48.59021 [2016-05-11 11:03:48,589][INFO ][node                     ] [Grand Director] version[1.7.5], pid[754], build[00f95f4/2016-02-02T09:55:30Z]
2016-05-11_15:03:48.59022 [2016-05-11 11:03:48,589][INFO ][node                     ] [Grand Director] initializing ...
2016-05-11_15:03:48.66302 [2016-05-11 11:03:48,662][INFO ][plugins                  ] [Grand Director] loaded [], sites [kopf]
2016-05-11_15:03:48.69405 [2016-05-11 11:03:48,693][INFO ][env                      ] [Grand Director] using [1] data paths, mounts [[/var/opt/graylog/data (/dev/xvdf1)]], net usable_space [43.1gb], net total_space [49gb], types [ext4]
2016-05-11_15:03:52.03198 [2016-05-11 11:03:52,031][INFO ][node                     ] [Grand Director] initialized
2016-05-11_15:03:52.03199 [2016-05-11 11:03:52,031][INFO ][node                     ] [Grand Director] starting ...
2016-05-11_15:03:52.22435 [2016-05-11 11:03:52,221][INFO ][transport                ] [Grand Director] bound_address {inet[/127.0.0.1:9300]}, publish_address {inet[/127.0.0.1:9300]}
2016-05-11_15:03:52.24953 [2016-05-11 11:03:52,248][INFO ][discovery                ] [Grand Director] graylog2/_fllMDX2TZOp6oi9rzNumw
2016-05-11_15:04:02.31608 [2016-05-11 11:04:02,315][INFO ][cluster.service          ] [Grand Director] new_master [Grand Director][_fllMDX2TZOp6oi9rzNumw][cddbff078b64][inet[/127.0.0.1:9300]], reason: zen-disco-join (elected_as_master)
2016-05-11_15:04:02.45754 [2016-05-11 11:04:02,457][INFO ][http                     ] [Grand Director] bound_address {inet[/127.0.0.1:9200]}, publish_address {inet[/127.0.0.1:9200]}
2016-05-11_15:04:02.45876 [2016-05-11 11:04:02,457][INFO ][node                     ] [Grand Director] started
2016-05-11_15:04:02.54209 [2016-05-11 11:04:02,541][INFO ][gateway                  ] [Grand Director] recovered [16] indices into cluster_state
2016-05-11_15:04:10.39269 [2016-05-11 11:04:10,391][INFO ][cluster.service          ] [Grand Director] added {[graylog2-server][H38j3Yp0Tfuo1DaF7gvCWQ][cddbff078b64][inet[/172.17.0.2:9350]]{client=true, data=false, master=false},}, reason: zen-disco-receive(join from node[[graylog2-server][H38j3Yp0Tfuo1DaF7gvCWQ][cddbff078b64][inet[/172.17.0.2:9350]]{client=true, data=false, master=false}])
2016-05-11_15:23:27.62069 [2016-05-11 11:23:27,615][INFO ][cluster.service          ] [Grand Director] removed {[graylog2-server][H38j3Yp0Tfuo1DaF7gvCWQ][cddbff078b64][inet[/172.17.0.2:9350]]{client=true, data=false, master=false},}, reason: zen-disco-node_left([graylog2-server][H38j3Yp0Tfuo1DaF7gvCWQ][cddbff078b64][inet[/172.17.0.2:9350]]{client=true, data=false, master=false})
2016-05-11_15:23:43.56848 [2016-05-11 11:23:43,563][INFO ][cluster.service          ] [Grand Director] added {[graylog2-server][FAQm4tLUR7KvLpdFpokE9Q][cddbff078b64][inet[/172.17.0.2:9350]]{client=true, data=false, master=false},}, reason: zen-disco-receive(join from node[[graylog2-server][FAQm4tLUR7KvLpdFpokE9Q][cddbff078b64][inet[/172.17.0.2:9350]]{client=true, data=false, master=false}])
2016-05-11_15:24:26.62793 [2016-05-11 11:24:26,626][INFO ][cluster.service          ] [Grand Director] removed {[graylog2-server][FAQm4tLUR7KvLpdFpokE9Q][cddbff078b64][inet[/172.17.0.2:9350]]{client=true, data=false, master=false},}, reason: zen-disco-node_left([graylog2-server][FAQm4tLUR7KvLpdFpokE9Q][cddbff078b64][inet[/172.17.0.2:9350]]{client=true, data=false, master=false})
2016-05-11_15:24:42.26578 [2016-05-11 11:24:42,264][INFO ][cluster.service          ] [Grand Director] added {[graylog2-server][ev7F_lGSQJey0NmmFNkZow][cddbff078b64][inet[/172.17.0.2:9350]]{client=true, data=false, master=false},}, reason: zen-disco-receive(join from node[[graylog2-server][ev7F_lGSQJey0NmmFNkZow][cddbff078b64][inet[/172.17.0.2:9350]]{client=true, data=false, master=false}])
```

**Comment by mariussturm** [comment]
OOM is definitely a problem. Please stop the GL server and make sure that the process is actually gone. In doubt `kill -9` the process. After a restart the server should continue to process messages.
You can also increase the heap size for the process, if you are using a pre-build appliance you can see here how to configure it: http://docs.graylog.org/en/2.0/pages/installation/graylog_ctl.html#advanced-settings

**Comment by mariussturm** [comment]
Closing this for now. Feel free to ping us again if the error shows up again with fixed memory settings.
