### ISSUE TITLE
graylog-ctl set-email-config fails

### ISSUE THREAD

**Issue by brandonegbert** [Graylog2/graylog2-images#132]
```
ubuntu@kt-graylog:~$ graylog-ctl set-email-config
(eval):33:in `block (2 levels) in load_files': undefined method `start_with?' for nil:NilClass (NoMethodError)
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:145:in `call'
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:145:in `block in add_command'
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:366:in `run'
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/bin/omnibus-ctl:27:in `<top (required)>'
        from /opt/graylog/embedded/bin/omnibus-ctl:23:in `load'
        from /opt/graylog/embedded/bin/omnibus-ctl:23:in `<main>'
```

**Comment by joschi** [comment]
@brandonegbert While the error message is certainly not good, you're simply missing a mandatory parameter for the `set-email-config` command, e. g. `sudo graylog-ctl set-email-config smtp.example.com`.

See http://docs.graylog.org/en/1.3/pages/installation/graylog_ctl.html#configuration-commands for details.

**Comment by brandonegbert** [comment]
Should it not display help text as all the other graylog-ctl commands do when used without parameters?

**Comment by mariussturm** [comment]
Yes, this will be fixed in the next release!
