### ISSUE TITLE
Docker: Failed to acquire lock on file .lock in /var/opt/graylog/data/journal

### ISSUE THREAD

**Issue by tnsasse** [Graylog2/graylog2-images#133]
I am trying to get a fresh graylog container working. I did the following steps:

```
$ docker pull graylog2/allinone
$ docker run -t -p 9000:9000 -p 12201:12201 -p 12201:12201/udp -e GRAYLOG_NODE_ID=graylog-0 -e GRAYLOG_SERVER_SECRET=salt0 -v /graylog/data:/var/opt/graylog/data -v /graylog/logs:/var/log/graylog -v /graylog/plugin:/opt/graylog/plugin graylog2/allinone
```

Now booting up the docker container, I see a lot of errors:

```
Running handlers complete
Chef Client finished, 117/132 resources updated in 84.084589629 seconds
graylog Reconfigured!
2016-03-19_11:30:33.90242   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-03-19_11:30:33.90326   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-03-19_11:30:33.90722   at java.lang.Thread.run(Thread.java:745)
2016-03-19_11:30:39.01736 INFO  [RestApiService] Adding security context factory: <org.graylog2.security.ShiroSecurityContextFactory@4891d7c8>
2016-03-19_11:30:39.05945 INFO  [RestApiService] Started REST API at <http://0.0.0.0:12900/>
2016-03-19_11:30:39.06989 INFO  [RestApiService] Shutting down REST API at <http://0.0.0.0:12900/>
2016-03-19_11:30:49.02214 It looks like you are trying to access MongoDB over HTTP on the native driver port.
2016-03-19_11:30:49.03374 Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
2016-03-19_11:30:49.03423 Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
2016-03-19_11:30:49.84888 INFO  [CmdLineTool] Running with JVM arguments: -Xms1g -Xmx1500m -XX:NewRatio=1 -XX:PermSize=128m -XX:MaxPermSize=256m -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -Dlog4j.configuration=file:///opt/graylog/conf/log4j.xml -Djava.library.path=/opt/graylog/server/lib/sigar/ -Dgraylog2.installation_source=docker
2016-03-19_11:30:56.92586 INFO  [LogManager] Loading logs.
2016-03-19_11:30:57.19159 ERROR [KafkaJournal] Unable to start logmanager.
2016-03-19_11:30:57.19160 kafka.common.KafkaException: Failed to acquire lock on file .lock in /var/opt/graylog/data/journal. A Kafka instance in another process or thread is using this directory.
```

Then nothing really happens, graylog seems not to come online. I am new to docker and graylog, thanks for help!

**Comment by tnsasse** [comment]
I deleted everything and tried setting up a new docker from within the Kitematic App and this ran without any problems. I am unsure though which kind of run command it issues. Appreciate it if anyone could shed some light on this, certainly there seems something wrong with my volume setup.

**Comment by klimashkin** [comment]
Same issue. @tnsasse what did you delete?

**Comment by Dids** [comment]
Also experiencing this. Even tried running with `privileged` on, but didn't change anything, even after removing all the files on the host.

**Comment by Dids** [comment]
Got it! Stop the container, then delete just the .lock file that's complaining about (on the host), start the container back up and it should stop complaining.

**Comment by Dids** [comment]
Well never mind that, it didn't work. Still throwing errors at a rate that's actually causing issues in my console.

**Comment by Dids** [comment]
"For anyone else who has this problem in the future the solution was to shutdown graylog delete /var/opt/graylog/data/journal/.kafka_cleanshutdown and restart"
- https://groups.google.com/forum/#!topic/graylog2/E-UYbP0v7JY

**Comment by mariussturm** [comment]
Thanks for the link @Dids, will close the ticket then.
