### ISSUE TITLE
2.0 AWS image cannot bind to external IP address

### ISSUE THREAD

**Issue by romanr** [Graylog2/graylog2-images#140]
Graylog 2.0 web interface thinks it need to use internal ip.
(Graylog 1.3 AWS image detects/works fine with external IP out-of-the-box.)

Installed ami-58b5af32
Assigned elastic ip. restarted.
run `graylog-ctl reconfigure`
restarted.

Open web interface,
in web console it's sending requests to internal ip address e.g.
`OPTIONS http://172.30.2.214:12900/system/cluster/node`
`http://172.30.2.214:12900/system/cluster/node net::ERR_CONNECTION_TIMED_OUT`

I found a config file
/etc/graylog/graylog-settings.json
changed ip address to external, 
graylog-ctl restart

didn't help. it still connects to internal.

**Comment by joschi** [comment]
@romanr Try setting the public IP address of your EC2 instance in `rest_listen_uri` and `web_listen_uri`.

See http://docs.graylog.org/en/2.0/pages/installation/graylog_ctl.html#advanced-settings and https://github.com/Graylog2/omnibus-graylog2/blob/2.0/files/graylog-cookbooks/graylog/attributes/default.rb#L62-L63 for information how to configure this.

**Comment by romanr** [comment]
Thanks for the answer. 
I edited https://github.com/Graylog2/omnibus-graylog2/blob/2.0/files/graylog-cookbooks/graylog/attributes/default.rb#L62-L63
changing 0.0.0.0 to host name of server. and added server_name in nginx.conf

Not sure what to do after default.rb is modified?
I ran `graylog-ctl reconfigure`.
After this I get the page "graylog is starting" forever.
Checked `graylog-ctl status` - all running
checked all logs, there are no errors.

It looks like a very trivial setup. I don't think many people running Graylog solely on private/default IP. Am I missing something obvious? Or it's just too early in beta to expect it working?

What am I doing wrong?

**Comment by joschi** [comment]
@romanr Please read the documentation section I've linked to in my last comment: http://docs.graylog.org/en/2.0/pages/installation/graylog_ctl.html#advanced-settings

**Comment by romanr** [comment]
Thank you for your answer! I am sorry I wasted your time because I missed that need to use "custom_attributes" in config file.

I am unable to get it working, please help:

We have DNS `logs.domain.com` pointing to external IP address.

changing custom_attributes in `/etc/graylog/graylog-settings.json`
running `graylog-ctl reconfigure;graylog-ctl restart` every time

```
 "custom_attributes": {
    "graylog-server": {
      "rest_listen_uri": "http://logs.domain.com:12900/",
      "web_listen_uri": "http://logs.domain.com:9000/"
    },
    "nginx": {
      "server_name": "logs.domain.com"
    }
```

Result in **"Graylog is restarting..."** forever

```
 "custom_attributes": {
    "graylog-server": {
      "rest_listen_uri": "http://logs.domain.com:12900/",
      "web_listen_uri": "http://logs.domain.com/"
    },
    "nginx": {
      "server_name": "logs.domain.com"
    }
```

Result in **"Graylog is restarting..."** forever

```
"custom_attributes": {
    "nginx": {
      "server_name": "logs.domain.com"
    }
  }
```

Results in connecting to internal IP: `http://172.30.2.214:12900/system/cluster/node net::ERR_CONNECTION_TIMED_OUT`

**Comment by joschi** [comment]
@romanr Can the host name `logs.domain.com` be resolved on the virtual machine hosting Graylog?

**Comment by romanr** [comment]
I think I may have found the issue. -  Graylog server is not compatible with virtual interfaces what AWS have

AWS EC2 have two interfaces, one for internal IP and loopback.
When you attach public or Elastic IP address to EC2 instance it does not appear in ifconfig,
here is the host with internal IP and External IP:

```
root@graylog:~# ifconfig
eth0      Link encap:Ethernet  HWaddr 12:66:56:4f:7f:ef
          inet addr:172.30.2.214  Bcast:172.30.2.255  Mask:255.255.255.0
          inet6 addr: fe80::1036:68bf:be4f:7f37/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:21583 errors:0 dropped:0 overruns:0 frame:0
          TX packets:16903 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1729551 (1.7 MB)  TX bytes:11993214 (11.9 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:578376 errors:0 dropped:0 overruns:0 frame:0
          TX packets:578376 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:153064871 (153.0 MB)  TX bytes:153064871 (153.0 MB)
```

As you can see there's no external IP or interface reported to network stack of operating system.

As soon as you configure any address that is not localhost or internal ip:

```
"custom_attributes": {
    "graylog-server": {
      "rest_listen_uri": "http:// <ADDRESS THAT IS NOT IN IFCONFIG >:12900/",
      "web_listen_uri": "http://<virtual ip>:9000/"
   }
```

it fails:

```
2016-04-28_11:06:41.00478 javax.ws.rs.ProcessingException: Failed to start Grizzly HTTP server: Cannot assign requested address
2016-04-28_11:06:41.00552   at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:299) ~[graylog.jar:?]
2016-04-28_11:06:41.00605   at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:163) ~[graylog.jar:?]
2016-04-28_11:06:41.02044   at org.graylog2.shared.initializers.AbstractJerseyService.setUp(AbstractJerseyService.java:158) ~[graylog.jar:?]
2016-04-28_11:06:41.02135   at org.graylog2.shared.initializers.RestApiService.startUp(RestApiService.java:65) ~[graylog.jar:?]
2016-04-28_11:06:41.02234   at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:60) [graylog.jar:?]
2016-04-28_11:06:41.03535   at com.google.common.util.concurrent.Callables$3.run(Callables.java:100) [graylog.jar:?]
2016-04-28_11:06:41.03602   at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
2016-04-28_11:06:41.03636 Caused by: java.net.BindException: Cannot assign requested address
2016-04-28_11:06:41.03694   at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_77]
2016-04-28_11:06:41.03738   at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_77]
2016-04-28_11:06:41.03785   at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_77]
2016-04-28_11:06:41.03875   at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_77]
2016-04-28_11:06:41.05176   at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_77]
2016-04-28_11:06:41.05177   at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bindToChannelAndAddress(TCPNIOBindingHandler.java:131) ~[graylog.jar:?]
2016-04-28_11:06:41.05256   at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bind(TCPNIOBindingHandler.java:88) ~[graylog.jar:?]
2016-04-28_11:06:41.06975   at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:248) ~[graylog.jar:?]
2016-04-28_11:06:41.07013   at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:228) ~[graylog.jar:?]
2016-04-28_11:06:41.07087   at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:219) ~[graylog.jar:?]
2016-04-28_11:06:41.07115   at org.glassfish.grizzly.http.server.NetworkListener.start(NetworkListener.java:714) ~[graylog.jar:?]
2016-04-28_11:06:41.08396   at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:278) ~[graylog.jar:?]
2016-04-28_11:06:41.08745   at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:296) ~[graylog.jar:?]
2016-04-28_11:06:41.10339   ... 6 more
2016-04-28_11:06:45.08723
2016-04-28_11:06:45.10250   at com.google.common.util.concurrent.AbstractService.awaitTerminated(AbstractService.java:280)
2016-04-28_11:06:45.10251   at com.google.common.util.concurrent.AbstractIdleService.awaitTerminated(AbstractIdleService.java:173)
2016-04-28_11:06:45.10275   at org.graylog2.system.shutdown.GracefulShutdown.doRun(GracefulShutdown.java:102)
2016-04-28_11:06:45.10389   at org.graylog2.system.shutdown.GracefulShutdown.runWithoutExit(GracefulShutdown.java:75)
2016-04-28_11:06:45.11260   at org.graylog2.commands.Server$ShutdownHook.run(Server.java:188)
2016-04-28_11:06:45.11375   at java.lang.Thread.run(Thread.java:745)
2016-04-28_11:06:45.11426 Caused by: javax.ws.rs.ProcessingException: Failed to start Grizzly HTTP server: Cannot assign requested address
2016-04-28_11:06:45.11488   at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:299)
2016-04-28_11:06:45.11538   at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:163)
2016-04-28_11:06:45.11590   at org.graylog2.shared.initializers.AbstractJerseyService.setUp(AbstractJerseyService.java:158)
2016-04-28_11:06:45.11640   at org.graylog2.shared.initializers.RestApiService.startUp(RestApiService.java:65)
2016-04-28_11:06:45.12941   at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:60)
2016-04-28_11:06:45.13069   at com.google.common.util.concurrent.Callables$3.run(Callables.java:100)
2016-04-28_11:06:45.13070   ... 1 more
2016-04-28_11:06:45.13107 Caused by: java.net.BindException: Cannot assign requested address
2016-04-28_11:06:45.13191   at sun.nio.ch.Net.bind0(Native Method)
2016-04-28_11:06:45.13237   at sun.nio.ch.Net.bind(Net.java:433)
2016-04-28_11:06:45.14552   at sun.nio.ch.Net.bind(Net.java:425)
2016-04-28_11:06:45.14595   at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
2016-04-28_11:06:45.14641   at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
2016-04-28_11:06:45.14711   at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bindToChannelAndAddress(TCPNIOBindingHandler.java:131)
2016-04-28_11:06:45.14764   at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bind(TCPNIOBindingHandler.java:88)
2016-04-28_11:06:45.14832   at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:248)
2016-04-28_11:06:45.14884   at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:228)
2016-04-28_11:06:45.16341   at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:219)
2016-04-28_11:06:45.16352   at org.glassfish.grizzly.http.server.NetworkListener.start(NetworkListener.java:714)
2016-04-28_11:06:45.16354   at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:278)
2016-04-28_11:06:45.16356   at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:296)
2016-04-28_11:06:45.16358   ... 6 more
2016-04-28_11:06:45.21218 It looks like you are trying to access MongoDB over HTTP on the native driver port.
```

**Comment by romanr** [comment]
Also, is it normal that it's doing this in the loop over and over:

```
2016-04-28_11:25:32.07397 It looks like you are trying to access MongoDB over HTTP on the native driver port.
2016-04-28_11:25:41.21279 2016-04-28 11:25:41,210 INFO : org.graylog2.bootstrap.CmdLineTool - Running with JVM arguments: -Xms1g -Xmx1500m -XX:NewRatio=1 -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -Dlog4j.configurationFile=file:///opt/graylog/conf/log4j2.xml -Djava.library.path=/opt/graylog/server/lib/sigar/ -Dgraylog2.installation_source=ami
2016-04-28_11:25:52.63047 2016-04-28 11:25:52,630 INFO : kafka.log.LogManager - Loading logs.
2016-04-28_11:25:53.34390 2016-04-28 11:25:53,343 INFO : kafka.log.LogManager - Logs loading complete.
2016-04-28_11:25:53.42437 2016-04-28 11:25:53,423 INFO : org.graylog2.shared.buffers.InputBufferImpl - Initialized InputBufferImpl with ring size <65536> and wait strategy <BlockingWaitStrategy>, running 2 parallel message handlers.
2016-04-28_11:25:54.04666 2016-04-28 11:25:54,026 INFO : org.mongodb.driver.connection - Opened connection [connectionId{localValue:1, serverValue:203}] to 127.0.0.1:27017
2016-04-28_11:25:54.06455 2016-04-28 11:25:54,044 INFO : org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 2, 5]}, minWireVersion=0, maxWireVersion=4, maxDocumentSize=16777216, roundTripTimeNanos=515162}
2016-04-28_11:26:03.18295 2016-04-28 11:26:03,182 INFO : org.elasticsearch.node - [graylog-ce35f8a1-26bc-4565-a041-cb58593bf247] initialized

```

**Comment by mariussturm** [comment]
We have updated the 2.0 AMIs, please take a look at the new `set-external-ip` command: http://docs.graylog.org/en/2.0/pages/installation/aws.html

**Comment by romanr** [comment]
It worked! Thank you for the great product!

**Comment by divyum** [comment]
@mariussturm how can we set external ip when setting up graylog manually (without VM), is there any key in server.conf I might need to add?

**Comment by joschi** [comment]
@divyum 
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by divyum** [comment]
@joschi will surely do so. Thanks. :)
