### ISSUE TITLE
Vagrant works but then has an issue after a period of time

### ISSUE THREAD

**Issue by agoodno** [Graylog2/graylog2-images#205]
Everything is working then after about 20 minutes of searching and indexing, I see this error in the UI:

```
Error Message:
    Unable to perform search query.
Details:
Search status code:
    500
Search response:
    cannot GET http://127.0.0.1:8080/api/search/universal/relative?query=%2A&range=300&limit=150&sort=timestamp%3Adesc (500)
```

Looking at the log I see:

> sudo tail -1000 /var/log/graylog/server/current
```text
2017-10-26_20:00:14.17938 ERROR [Messages] Caught exception during bulk indexing: io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://10.0.2.15:9200, retrying (attempt #21).
2017-10-26_20:00:14.30715 INFO  [IndexRetentionThread] Elasticsearch cluster not available, skipping index retention checks.
2017-10-26_20:00:14.31132 ERROR [Cluster] Couldn't read cluster health for indices [graylog_*] (Could not connect to http://10.0.2.15:9200)
2017-10-26_20:00:14.31621 INFO  [IndexerClusterCheckerThread] Indexer not fully initialized yet. Skipping periodic cluster check.
2017-10-26_20:00:15.90712 ERROR [Messages] Caught exception during bulk indexing: io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://10.0.2.15:9200, retrying (attempt #16).
2017-10-26_20:00:25.89311 ERROR [Messages] Caught exception during bulk indexing: io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://10.0.2.15:9200, retrying (attempt #18).
2017-10-26_20:00:34.83411 ERROR [Messages] Caught exception during bulk indexing: io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://10.0.2.15:9200, retrying (attempt #20).
2017-10-26_20:00:42.12991 ERROR [NodeChecker] Connect exception executing NodesInfo!
2017-10-26_20:00:42.13000 io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://10.0.2.15:9200
2017-10-26_20:00:42.13064 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:80) ~[graylog.jar:?]
2017-10-26_20:00:42.13201 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:64) ~[graylog.jar:?]
2017-10-26_20:00:42.13471 	at io.searchbox.client.config.discovery.NodeChecker.runOneIteration(NodeChecker.java:65) [graylog.jar:?]
2017-10-26_20:00:42.13618 	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:188) [graylog.jar:?]
2017-10-26_20:00:42.14011 	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122) [graylog.jar:?]
2017-10-26_20:00:42.14155 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
2017-10-26_20:00:42.14210 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
2017-10-26_20:00:42.14737 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
2017-10-26_20:00:42.14820 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
2017-10-26_20:00:42.14970 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
2017-10-26_20:00:42.15459 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
2017-10-26_20:00:42.15560 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
2017-10-26_20:00:42.15603 Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 10.0.2.15:9200 [/10.0.2.15] failed: Connection refused (Connection refused)
2017-10-26_20:00:42.15700 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159) ~[graylog.jar:?]
2017-10-26_20:00:42.15785 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[graylog.jar:?]
2017-10-26_20:00:42.16280 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[graylog.jar:?]
2017-10-26_20:00:42.16314 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[graylog.jar:?]
2017-10-26_20:00:42.16391 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[graylog.jar:?]
2017-10-26_20:00:42.16423 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[graylog.jar:?]
2017-10-26_20:00:42.16490 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[graylog.jar:?]
2017-10-26_20:00:42.16515 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[graylog.jar:?]
2017-10-26_20:00:42.16572 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[graylog.jar:?]
2017-10-26_20:00:42.16594 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[graylog.jar:?]
2017-10-26_20:00:42.16754 	at io.searchbox.client.http.JestHttpClient.executeRequest(JestHttpClient.java:151) ~[graylog.jar:?]
2017-10-26_20:00:42.16758 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:77) ~[graylog.jar:?]
2017-10-26_20:00:42.16817 	... 11 more
2017-10-26_20:00:42.16838 Caused by: java.net.ConnectException: Connection refused (Connection refused)
2017-10-26_20:00:42.17763 	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_151]
2017-10-26_20:00:42.17784 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_151]
2017-10-26_20:00:42.17829 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_151]
2017-10-26_20:00:42.17850 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_151]
2017-10-26_20:00:42.17893 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_151]
2017-10-26_20:00:42.17909 	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_151]
2017-10-26_20:00:42.17951 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75) ~[graylog.jar:?]
2017-10-26_20:00:42.17967 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[graylog.jar:?]
2017-10-26_20:00:42.18001 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[graylog.jar:?]
2017-10-26_20:00:42.18015 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[graylog.jar:?]
2017-10-26_20:00:42.18040 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[graylog.jar:?]
2017-10-26_20:00:42.18040 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[graylog.jar:?]
2017-10-26_20:00:42.18063 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[graylog.jar:?]
2017-10-26_20:00:42.18080 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[graylog.jar:?]
2017-10-26_20:00:42.18121 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[graylog.jar:?]
2017-10-26_20:00:42.18135 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[graylog.jar:?]
2017-10-26_20:00:42.18178 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[graylog.jar:?]
2017-10-26_20:00:42.18198 	at io.searchbox.client.http.JestHttpClient.executeRequest(JestHttpClient.java:151) ~[graylog.jar:?]
2017-10-26_20:00:42.18237 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:77) ~[graylog.jar:?]
2017-10-26_20:00:42.18251 	... 11 more
2017-10-26_20:00:42.18841 WARN  [NodeChecker] Removing host http://10.0.2.15:9200
2017-10-26_20:00:42.18868 INFO  [NodeChecker] Discovered server pool is now: 
2017-10-26_20:00:44.18357 ERROR [Messages] Caught exception during bulk indexing: io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://10.0.2.15:9200, retrying (attempt #22).
2017-10-26_20:00:44.30636 ERROR [Cluster] Couldn't read cluster health for indices [graylog_*] (Could not connect to http://10.0.2.15:9200)
2017-10-26_20:00:44.30688 INFO  [IndexerClusterCheckerThread] Indexer not fully initialized yet. Skipping periodic cluster check.
2017-10-26_20:00:45.93524 ERROR [Messages] Caught exception during bulk indexing: io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://10.0.2.15:9200, retrying (attempt #17).
2017-10-26_20:00:51.13276 WARN  [GelfCodec] GELF message <5ddf18b0-ba88-11e7-8086-080027b2ac87> (received from <10.0.2.2:49438>) has invalid "timestamp": 1509048047.207  (type: STRING)
2017-10-26_20:00:55.91872 ERROR [Messages] Caught exception during bulk indexing: io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://10.0.2.15:9200, retrying (attempt #19).
2017-10-26_20:00:58.07691 WARN  [GelfCodec] GELF message <6202aab0-ba88-11e7-8086-080027b2ac87> (received from <10.0.2.2:49438>) has invalid "timestamp": 1509048054.147  (type: STRING)
2017-10-26_20:01:04.85925 ERROR [Messages] Caught exception during bulk indexing: io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://10.0.2.15:9200, retrying (attempt #21).
2017-10-26_20:01:12.19534 ERROR [NodeChecker] Connect exception executing NodesInfo!
2017-10-26_20:01:12.19584 io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://10.0.2.15:9200
2017-10-26_20:01:12.19735 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:80) ~[graylog.jar:?]
2017-10-26_20:01:12.19819 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:64) ~[graylog.jar:?]
2017-10-26_20:01:12.20365 	at io.searchbox.client.config.discovery.NodeChecker.runOneIteration(NodeChecker.java:65) [graylog.jar:?]
2017-10-26_20:01:12.20431 	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:188) [graylog.jar:?]
2017-10-26_20:01:12.20573 	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122) [graylog.jar:?]
2017-10-26_20:01:12.20632 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
2017-10-26_20:01:12.21120 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
2017-10-26_20:01:12.21181 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
2017-10-26_20:01:12.21323 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
2017-10-26_20:01:12.21646 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
2017-10-26_20:01:12.21782 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
2017-10-26_20:01:12.22170 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
2017-10-26_20:01:12.22273 Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 10.0.2.15:9200 [/10.0.2.15] failed: Connection refused (Connection refused)
2017-10-26_20:01:12.22313 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159) ~[graylog.jar:?]
2017-10-26_20:01:12.22405 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[graylog.jar:?]
2017-10-26_20:01:12.22442 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[graylog.jar:?]
2017-10-26_20:01:12.22954 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[graylog.jar:?]
2017-10-26_20:01:12.22991 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[graylog.jar:?]
2017-10-26_20:01:12.23058 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[graylog.jar:?]
2017-10-26_20:01:12.23082 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[graylog.jar:?]
2017-10-26_20:01:12.23142 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[graylog.jar:?]
2017-10-26_20:01:12.23165 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[graylog.jar:?]
2017-10-26_20:01:12.23224 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[graylog.jar:?]
2017-10-26_20:01:12.23247 	at io.searchbox.client.http.JestHttpClient.executeRequest(JestHttpClient.java:151) ~[graylog.jar:?]
2017-10-26_20:01:12.23586 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:77) ~[graylog.jar:?]
2017-10-26_20:01:12.23609 	... 11 more
2017-10-26_20:01:12.23659 Caused by: java.net.ConnectException: Connection refused (Connection refused)
2017-10-26_20:01:12.23679 	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_151]
2017-10-26_20:01:12.23728 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_151]
2017-10-26_20:01:12.23750 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_151]
2017-10-26_20:01:12.23798 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_151]
2017-10-26_20:01:12.23819 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_151]
2017-10-26_20:01:12.24320 	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_151]
2017-10-26_20:01:12.24320 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75) ~[graylog.jar:?]
2017-10-26_20:01:12.24358 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[graylog.jar:?]
2017-10-26_20:01:12.24375 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[graylog.jar:?]
2017-10-26_20:01:12.24415 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[graylog.jar:?]
2017-10-26_20:01:12.24432 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[graylog.jar:?]
2017-10-26_20:01:12.24473 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[graylog.jar:?]
2017-10-26_20:01:12.24491 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[graylog.jar:?]
2017-10-26_20:01:12.24528 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[graylog.jar:?]
2017-10-26_20:01:12.24542 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[graylog.jar:?]
2017-10-26_20:01:12.24578 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[graylog.jar:?]
2017-10-26_20:01:12.24592 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[graylog.jar:?]
2017-10-26_20:01:12.24627 	at io.searchbox.client.http.JestHttpClient.executeRequest(JestHttpClient.java:151) ~[graylog.jar:?]
2017-10-26_20:01:12.24640 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:77) ~[graylog.jar:?]
2017-10-26_20:01:12.24675 	... 11 more
2017-10-26_20:01:12.24976 WARN  [NodeChecker] Removing host http://10.0.2.15:9200
2017-10-26_20:01:12.25042 INFO  [NodeChecker] Discovered server pool is now: 
2017-10-26_20:01:14.18904 ERROR [Messages] Caught exception during bulk indexing: io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://10.0.2.15:9200, retrying (attempt #23).
2017-10-26_20:01:14.31138 ERROR [Cluster] Couldn't read cluster health for indices [graylog_*] (Could not connect to http://10.0.2.15:9200)
2017-10-26_20:01:14.31499 INFO  [IndexerClusterCheckerThread] Indexer not fully initialized yet. Skipping periodic cluster check.
2017-10-26_20:01:15.96583 ERROR [Messages] Caught exception during bulk indexing: io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://10.0.2.15:9200, retrying (attempt #18).
2017-10-26_20:01:25.94875 ERROR [Messages] Caught exception during bulk indexing: io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://10.0.2.15:9200, retrying (attempt #20).
```

then after halting the vagrant box and bringing it back up I'm getting in the log:

```text
2017-10-27_13:47:58.34169 ERROR [DecodingProcessor] Error processing message RawMessage{id=5cfb0cc0-baf5-11e7-ae89-080027b2ac87, journalOffset=3308069, codec=gelf, payloadSize=140, timestamp=2017-10-27T09:01:04.780Z, remoteAddress=/127.0.0.1:45415}
2017-10-27_13:47:58.34227 java.lang.IllegalArgumentException: GELF message <5cfb0cc0-baf5-11e7-ae89-080027b2ac87> (received from <127.0.0.1:45415>) has empty mandatory "short_message" field.
2017-10-27_13:47:58.34246 	at org.graylog2.inputs.codecs.GelfCodec.validateGELFMessage(GelfCodec.java:252) ~[graylog.jar:?]
2017-10-27_13:47:58.34283 	at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:134) ~[graylog.jar:?]
2017-10-27_13:47:58.34301 	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:146) ~[graylog.jar:?]
2017-10-27_13:47:58.34337 	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:87) [graylog.jar:?]
2017-10-27_13:47:58.34353 	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:74) [graylog.jar:?]
2017-10-27_13:47:58.34388 	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:42) [graylog.jar:?]
2017-10-27_13:47:58.34406 	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
2017-10-27_13:47:58.34443 	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
2017-10-27_13:47:58.34461 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
2017-10-27_13:47:58.34509 ERROR [DecodingProcessor] Unable to decode raw message RawMessage{id=5cfba900-baf5-11e7-ae89-080027b2ac87, journalOffset=3308087, codec=gelf, payloadSize=140, timestamp=2017-10-27T09:01:04.784Z, remoteAddress=/127.0.0.1:45415} on input <59f2093f60413d0d0a79830c>.
2017-10-27_13:47:58.34551 ERROR [DecodingProcessor] Error processing message RawMessage{id=5cfba900-baf5-11e7-ae89-080027b2ac87, journalOffset=3308087, codec=gelf, payloadSize=140, timestamp=2017-10-27T09:01:04.784Z, remoteAddress=/127.0.0.1:45415}
2017-10-27_13:47:58.34590 java.lang.IllegalArgumentException: GELF message <5cfba900-baf5-11e7-ae89-080027b2ac87> (received from <127.0.0.1:45415>) has empty mandatory "short_message" field.
2017-10-27_13:47:58.34607 	at org.graylog2.inputs.codecs.GelfCodec.validateGELFMessage(GelfCodec.java:252) ~[graylog.jar:?]
2017-10-27_13:47:58.34642 	at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:134) ~[graylog.jar:?]
2017-10-27_13:47:58.34658 	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:146) ~[graylog.jar:?]
2017-10-27_13:47:58.34692 	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:87) [graylog.jar:?]
2017-10-27_13:47:58.34708 	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:74) [graylog.jar:?]
2017-10-27_13:47:58.34742 	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:42) [graylog.jar:?]
2017-10-27_13:47:58.34756 	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
2017-10-27_13:47:58.35094 	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
2017-10-27_13:47:58.35115 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
2017-10-27_13:47:58.35753 ERROR [DecodingProcessor] Unable to decode raw message RawMessage{id=5cfedd50-baf5-11e7-ae89-080027b2ac87, journalOffset=3308172, codec=gelf, payloadSize=141, timestamp=2017-10-27T09:01:04.805Z, remoteAddress=/127.0.0.1:45415} on input <59f2093f60413d0d0a79830c>.
```
I'm not sure if it's all related.

**Comment by mariussturm** [comment]
Hi,
it looks like your Elasticsearch service is not running anymore. Small VMs tend to run out of disk space at some point. Take a look at the Es log file for further debugging.

**Comment by agoodno** [comment]
Thanks, I've bumped up the VM's memory and I'll watch the ES log for issues.

**Comment by mariussturm** [comment]
Alright, closing for now.
