### ISSUE TITLE
 java.net.ConnectException: Connection refused: /127.0.0.1:12900 to http://127.0.0.1:12900/system/cluster/node

### ISSUE THREAD

**Issue by sophiaso** [Graylog2/graylog2-images#43]
I don't know if I have missed anything, when I tried to start the docker container with below two steps:

docker pull graylog2/allinone
docker run -t -p 9000:9000 -p 12201:12201 graylog2/allinone

docker version: 1.3.4
OS: centos 6 x86_64
```
 netstat -ltn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address               Foreign Address             State
tcp        0      0 0.0.0.0:80                  0.0.0.0:*                   LISTEN
tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN
tcp        0      0 127.0.0.1:25                0.0.0.0:*                   LISTEN
tcp        0      0 :::9000                     :::*                        LISTEN
tcp        0      0 :::12201                    :::*                        LISTEN
tcp        0      0 :::9200                     :::*                        LISTEN
tcp        0      0 :::9300                     :::*                        LISTEN
tcp        0      0 :::5044                     :::*                        LISTEN
tcp        0      0 :::9301                     :::*                        LISTEN
tcp        0      0 :::9302                     :::*                        LISTEN
tcp        0      0 :::22                       :::*                        LISTEN
tcp        0      0 :::9303                     :::*                        LISTEN
```
Yes, the 12900 port is not listening.

I always failed with below exception:
```
2015-03-04_05:47:05.38666 java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: /127.0.0.1:12900 to http://127.0.0.1:12900/system/cluster/node
2015-03-04_05:47:05.38667       at com.ning.http.client.providers.netty.NettyResponseFuture.abort(NettyResponseFuture.java:342) ~[com.ning.async-http-client-1.8.14.jar:na]
2015-03-04_05:47:05.38668       at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:108) ~[com.ning.async-http-client-1.8.14.jar:na]
2015-03-04_05:47:05.38669       at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:431) ~[io.netty.netty-3.9.3.Final.jar:na]
2015-03-04_05:47:05.38670       at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:422) ~[io.netty.netty-3.9.3.Final.jar:na]
2015-03-04_05:47:05.38671       at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:384) ~[io.netty.netty-3.9.3.Final.jar:na]
2015-03-04_05:47:05.38672 Caused by: java.net.ConnectException: Connection refused: /127.0.0.1:12900 to http://127.0.0.1:12900/system/cluster/node
2015-03-04_05:47:05.38675       at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:104) ~[com.ning.async-http-client-1.8.14.jar:na]
2015-03-04_05:47:05.38676       at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:431) ~[io.netty.netty-3.9.3.Final.jar:na]
2015-03-04_05:47:05.38677       at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:422) ~[io.netty.netty-3.9.3.Final.jar:na]
2015-03-04_05:47:05.38678       at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:384) ~[io.netty.netty-3.9.3.Final.jar:na]
2015-03-04_05:47:05.38678       at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109) ~[io.netty.netty-3.9.3.Final.jar:na]
2015-03-04_05:47:05.38679 Caused by: java.net.ConnectException: Connection refused: /127.0.0.1:12900
2015-03-04_05:47:05.38680       at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.7.0_71]
2015-03-04_05:47:05.38680       at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739) ~[na:1.7.0_71]
2015-03-04_05:47:05.38681       at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152) ~[io.netty.netty-3.9.3.Final.jar:na]
2015-03-04_05:47:05.38683       at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105) ~[io.netty.netty-3.9.3.Final.jar:na]
2015-03-04_05:47:05.38684       at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79) ~[io.netty.netty-3.9.3.Final.jar:na]
```
so does this mean the rest_listen_uri is using http://0.0.0.0:12900/, as some other post related with this issue, it should be http://127.0.0.1:12900/.
Is there any way I can configure this or any option for the run command? I could not find.

Thanks,
Sophia

**Comment by mariussturm** [comment]
The most common problem is that Elasticsearch is not running properly and as a side effect Graylog server can not start. That's why nothing is listening on port 12900. Did you make sure to give enough memory to the host system? You need 3-4 Gig to run all components.

**Comment by sophiaso** [comment]
@mariussturm thanks for your reply. I was thinking it might be caused by the low memory, it was 3.75G. But I didn't get any error log related with this. I tried with another server with 7.5G memory, still failed with same error. If there is no other possible reasons, will try this again tomorrow. Though I have tried many times already...  I tried to start the server  container and web interface container separately, this time, I can find the 12900 port listening, but the web interface still failed to connect with the graylog server.

**Comment by mariussturm** [comment]
Odd, tried with Centos 6 and everything went smoothly.

**Comment by sophiaso** [comment]
I am using Amazon EC2, will this be different? Thanks. I can not use the amazon ami, as I didn't find any in ap-northeast zone

**Comment by mariussturm** [comment]
Amazon machines are sometimes kind of slow. This can produce more problems than running Graylog on your own hardware. Maybe you can double check the Docker image with a local host e.g. boot2docker machine?

**Comment by sophiaso** [comment]
Just tried on Mac OS with boot2docker, succeeded and can access with {boot2docker ip}:9000, though I still saw error:
<pre>Connection refused: /127.0.0.1:12900 to http://127.0.0.1:12900/system/cluster/node</pre>
But it's a successful start, as you mentioned that amazon is slow, so I should configure graylog by myself without using docker and ami? Thank you.

**Comment by mariussturm** [comment]
Yes, I think Docker on a AWS machine is the problem here. Please follow one of our normal install routines!
