### ISSUE TITLE
Support cloud-aws Elasticsearch Plugin Within Graylog ES Client

### ISSUE THREAD

**Issue by brandongalbraith** [Graylog2/graylog2-images#58]
I'm able to install [cloud-aws](https://github.com/elastic/elasticsearch-cloud-aws) within the Docker container, but the Graylog ES client is unable to use the ec2 discovery method to locate other nodes within the ES cluster.

When providing the below options in `graylog-elasticsearch.yml` (specified in graylog.conf), the Graylog server errors out:

```
cluster.name: <clusterName>
discovery.ec2.groups: <securityGroup>
discovery.ec2.tag.role: <instanceRole>
discovery.type: ec2
```

```
2015-05-12_06:06:42.62617 ERROR [CmdLineTool] Guice error (more detail on log level debug): Tried proxying org.graylog2.outputs.OutputRegistry to support a circular dependency, but it is not an interface.
2015-05-12_06:06:42.62631 Exception in thread "main" com.google.inject.CreationException: Guice creation errors:
2015-05-12_06:06:42.79681 
2015-05-12_06:06:42.79682 1) Error in custom provider, org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class setting [discovery.type] with value [ec2]
2015-05-12_06:06:42.79683   while locating org.graylog2.bindings.providers.EsNodeProvider
2015-05-12_06:06:42.79684   at org.graylog2.bindings.ServerBindings.bindSingletons(ServerBindings.java:151)
2015-05-12_06:06:42.79685   while locating org.elasticsearch.node.Node
2015-05-12_06:06:42.79685     for parameter 0 at org.graylog2.indexer.messages.Messages.<init>(Messages.java:63)
2015-05-12_06:06:42.79686   at org.graylog2.indexer.messages.Messages.class(Messages.java:56)
2015-05-12_06:06:42.79687   while locating org.graylog2.indexer.messages.Messages
2015-05-12_06:06:42.79688     for parameter 1 at org.graylog2.outputs.BlockingBatchedESOutput.<init>(BlockingBatchedESOutput.java:76)
2015-05-12_06:06:42.79688   while locating org.graylog2.outputs.BlockingBatchedESOutput
2015-05-12_06:06:42.79689   at org.graylog2.bindings.MessageOutputBindings.configure(MessageOutputBindings.java:48)
2015-05-12_06:06:42.79690   while locating org.graylog2.plugin.outputs.MessageOutput annotated with @org.graylog2.outputs.DefaultMessageOutput()
2015-05-12_06:06:42.79691     for parameter 0 at org.graylog2.outputs.OutputRegistry.<init>(OutputRegistry.java:69)
2015-05-12_06:06:42.79694   at org.graylog2.outputs.OutputRegistry.class(OutputRegistry.java:49)
2015-05-12_06:06:42.79695   while locating org.graylog2.outputs.OutputRegistry
2015-05-12_06:06:42.79696     for parameter 2 at org.graylog2.streams.OutputServiceImpl.<init>(OutputServiceImpl.java:48)
2015-05-12_06:06:42.79697   while locating org.graylog2.streams.OutputServiceImpl
2015-05-12_06:06:42.79698   while locating org.graylog2.streams.OutputService
2015-05-12_06:06:42.79699     for parameter 3 at org.graylog2.streams.StreamServiceImpl.<init>(StreamServiceImpl.java:63)
2015-05-12_06:06:42.79700   while locating org.graylog2.streams.StreamServiceImpl
2015-05-12_06:06:42.79701   while locating org.graylog2.streams.StreamService
2015-05-12_06:06:42.79702     for parameter 1 at org.graylog2.periodical.AlertScannerThread.<init>(AlertScannerThread.java:56)
2015-05-12_06:06:42.79703   while locating org.graylog2.periodical.AlertScannerThread
2015-05-12_06:06:42.79704   while locating org.graylog2.plugin.periodical.Periodical annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=102)
2015-05-12_06:06:42.79705   at org.graylog2.shared.bindings.SharedPeriodicalBindings.configure(SharedPeriodicalBindings.java:30)
2015-05-12_06:06:42.79706   while locating java.util.Set<org.graylog2.plugin.periodical.Periodical>
2015-05-12_06:06:42.79709     for parameter 2 at org.graylog2.shared.initializers.PeriodicalsService.<init>(PeriodicalsService.java:50)
2015-05-12_06:06:42.79710   at org.graylog2.shared.initializers.PeriodicalsService.class(PeriodicalsService.java:40)
2015-05-12_06:06:42.79711   while locating org.graylog2.shared.initializers.PeriodicalsService
2015-05-12_06:06:42.79714   while locating com.google.common.util.concurrent.Service annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=3)
2015-05-12_06:06:42.79715   at org.graylog2.shared.bindings.GenericInitializerBindings.configure(GenericInitializerBindings.java:30)
2015-05-12_06:06:42.79716   while locating java.util.Set<com.google.common.util.concurrent.Service>
2015-05-12_06:06:42.79717     for field at org.graylog2.shared.bindings.providers.ServiceManagerProvider.services(ServiceManagerProvider.java:33)
2015-05-12_06:06:42.79719   while locating org.graylog2.shared.bindings.providers.ServiceManagerProvider
2015-05-12_06:06:42.79720   at org.graylog2.shared.bindings.GenericBindings.configure(GenericBindings.java:70)
2015-05-12_06:06:42.79720   while locating com.google.common.util.concurrent.ServiceManager
2015-05-12_06:06:42.79721 Caused by: org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class setting [discovery.type] with value [ec2]
2015-05-12_06:06:42.79723 	at org.elasticsearch.common.settings.ImmutableSettings.loadClass(ImmutableSettings.java:471)
2015-05-12_06:06:42.79724 	at org.elasticsearch.common.settings.ImmutableSettings.getAsClass(ImmutableSettings.java:459)
2015-05-12_06:06:42.79725 	at org.elasticsearch.discovery.DiscoveryModule.spawnModules(DiscoveryModule.java:53)
2015-05-12_06:06:42.79726 	at org.elasticsearch.common.inject.ModulesBuilder.add(ModulesBuilder.java:44)
2015-05-12_06:06:42.79728 	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:171)
2015-05-12_06:06:42.79728 	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
2015-05-12_06:06:42.79729 	at org.graylog2.bindings.providers.EsNodeProvider.get(EsNodeProvider.java:57)
2015-05-12_06:06:42.79730 	at org.graylog2.bindings.providers.EsNodeProvider.get(EsNodeProvider.java:40)
2015-05-12_06:06:42.79731 	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:55)
2015-05-12_06:06:42.79731 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
2015-05-12_06:06:42.79732 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
2015-05-12_06:06:42.79734 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2015-05-12_06:06:42.79735 	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
2015-05-12_06:06:42.79736 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
2015-05-12_06:06:42.79736 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
2015-05-12_06:06:42.79737 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
2015-05-12_06:06:42.79738 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
2015-05-12_06:06:42.79739 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
2015-05-12_06:06:42.79739 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
2015-05-12_06:06:42.79740 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
2015-05-12_06:06:42.79741 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2015-05-12_06:06:42.79742 	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
2015-05-12_06:06:42.79743 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
2015-05-12_06:06:42.79745 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
2015-05-12_06:06:42.79746 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
2015-05-12_06:06:42.79747 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
2015-05-12_06:06:42.79748 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
2015-05-12_06:06:42.79751 	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
2015-05-12_06:06:42.79752 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
2015-05-12_06:06:42.79753 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
2015-05-12_06:06:42.79754 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2015-05-12_06:06:42.79755 	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
2015-05-12_06:06:42.79756 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
2015-05-12_06:06:42.79757 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
2015-05-12_06:06:42.79760 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
2015-05-12_06:06:42.79761 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
2015-05-12_06:06:42.79762 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
2015-05-12_06:06:42.79763 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
2015-05-12_06:06:42.79764 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
2015-05-12_06:06:42.79765 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2015-05-12_06:06:42.79766 	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
2015-05-12_06:06:42.79767 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
2015-05-12_06:06:42.79768 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
2015-05-12_06:06:42.79769 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
2015-05-12_06:06:42.79773 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
2015-05-12_06:06:42.79774 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
2015-05-12_06:06:42.79775 	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:737)
2015-05-12_06:06:42.79776 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
2015-05-12_06:06:42.79777 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
2015-05-12_06:06:42.79778 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
2015-05-12_06:06:42.79779 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
2015-05-12_06:06:42.79780 	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
2015-05-12_06:06:42.79781 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
2015-05-12_06:06:42.79782 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
2015-05-12_06:06:42.79783 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
2015-05-12_06:06:42.79784 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
2015-05-12_06:06:42.79786 	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
2015-05-12_06:06:42.79787 	at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
2015-05-12_06:06:42.79788 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
2015-05-12_06:06:42.79789 	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
2015-05-12_06:06:42.79790 	at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:326)
2015-05-12_06:06:42.79791 	at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:220)
2015-05-12_06:06:42.79793 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
2015-05-12_06:06:42.79794 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
2015-05-12_06:06:42.79795 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
2015-05-12_06:06:42.79796 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
2015-05-12_06:06:42.79797 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
2015-05-12_06:06:42.79798 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
2015-05-12_06:06:42.79799 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
2015-05-12_06:06:42.79800 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2015-05-12_06:06:42.79800 	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
2015-05-12_06:06:42.79801 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
2015-05-12_06:06:42.79802 	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
2015-05-12_06:06:42.79802 	at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
2015-05-12_06:06:42.79803 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
2015-05-12_06:06:42.79804 	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
2015-05-12_06:06:42.79804 	at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:326)
2015-05-12_06:06:42.79805 	at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:220)
2015-05-12_06:06:42.79806 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
2015-05-12_06:06:42.79807 	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:53)
2015-05-12_06:06:42.79808 	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
2015-05-12_06:06:42.79809 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:94)
2015-05-12_06:06:42.79809 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
2015-05-12_06:06:42.79810 	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:53)
2015-05-12_06:06:42.79811 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
2015-05-12_06:06:42.79812 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
2015-05-12_06:06:42.79813 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2015-05-12_06:06:42.79814 	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
2015-05-12_06:06:42.79815 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
2015-05-12_06:06:42.79816 	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:204)
2015-05-12_06:06:42.79818 	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:198)
2015-05-12_06:06:42.79818 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
2015-05-12_06:06:42.79819 	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:198)
2015-05-12_06:06:42.79820 	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:179)
2015-05-12_06:06:42.79820 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
2015-05-12_06:06:42.79821 	at com.google.inject.Guice.createInjector(Guice.java:95)
2015-05-12_06:06:42.79822 	at com.google.inject.Guice.createInjector(Guice.java:72)
2015-05-12_06:06:42.79823 	at org.graylog2.shared.bindings.Hk2GuiceBridgeJitInjector.create(Hk2GuiceBridgeJitInjector.java:59)
2015-05-12_06:06:42.79824 	at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:32)
2015-05-12_06:06:42.79825 	at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:353)
2015-05-12_06:06:42.79826 	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:175)
2015-05-12_06:06:42.79827 	at org.graylog2.bootstrap.Main.main(Main.java:58)
2015-05-12_06:06:42.79829 Caused by: java.lang.ClassNotFoundException: org.elasticsearch.discovery.ec2.Ec2DiscoveryModule
2015-05-12_06:06:42.79830 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2015-05-12_06:06:42.79831 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2015-05-12_06:06:42.79832 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2015-05-12_06:06:42.79833 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2015-05-12_06:06:42.79834 	at org.elasticsearch.common.settings.ImmutableSettings.loadClass(ImmutableSettings.java:469)
2015-05-12_06:06:42.79835 	... 101 more
```

**Comment by mariussturm** [comment]
I think this is a general problem with Docker on EC2. The ES plugin is making use of the EC2 metadata to publish cluster informations. But the metadata is not accessable inside of a container. There are projects like this you could try: https://github.com/dump247/docker-ec2-metadata
Or you go with the native EC2 instance of the Graylog appliance: https://github.com/Graylog2/graylog2-images/tree/master/aws

**Comment by brandongalbraith** [comment]
@mariussturm It looks like graylog-server is using the 1.3.2 version of the Elasticsearch client (https://github.com/Graylog2/graylog2-server/blob/1.0.2/pom.xml#L223), but the omnibus install is using 1.4.5, hence the exceptions about not finding an injectable constructor.

**Comment by mariussturm** [comment]
Yeah, the linked client library is always a little bit behind. Depends on when the server binary was compiled. But of cause we try to run a recent version of ES. Did you install the plugin for the Graylog-Server as well?

**Comment by brandongalbraith** [comment]
I was successful in using the `elasticsearch/elasticsearch-cloud-aws/2.4.1` version of the cloud-aws plugin, but from a Docker container built from a new Dockerfile that installed components individually instead of using the omnibus deb package.
