### ISSUE TITLE
Doesn't work out of box

### ISSUE THREAD

**Issue by leonty** [Graylog2/graylog2-images#81]
Run as (I don't need exposing ports):
> docker run -t graylog2/allinone

Result: the server is not started, keeps terminating and restarting.

Some info:
Processes in the container:

root@44ecbb92fd9a:/# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 13:36 ?        00:00:00 /usr/bin/python3 -u /opt/graylog/embedded/share/docker/my_init
root         6     1  0 13:36 ?        00:00:00 /opt/graylog/embedded/bin/runsvdir -P /opt/graylog/sv
root       212     6  0 13:36 ?        00:00:00 runsv etcd
root       213   212  0 13:36 ?        00:00:00 svlogd -tt /var/log/graylog/etcd
graylog    214   212  0 13:36 ?        00:00:01 /opt/graylog/embedded/sbin/etcd -listen-client-urls=http://0.0.0.0:2379,http
root       227     6  0 13:36 ?        00:00:00 runsv elasticsearch
root       228   227  0 13:36 ?        00:00:00 svlogd -tt /var/log/graylog/elasticsearch
root       296     6  0 13:36 ?        00:00:00 runsv mongodb
root       297   296  0 13:36 ?        00:00:00 svlogd -tt /var/log/graylog/mongodb
graylog    298   296  0 13:36 ?        00:00:02 /opt/graylog/mongodb/bin/mongod --dbpath /var/opt/graylog/data/mongodb --sma
root       327     6  0 13:36 ?        00:00:00 runsv graylog-server
root       328   327  0 13:36 ?        00:00:00 svlogd -tt /var/log/graylog/server
root       370     6  0 13:36 ?        00:00:00 runsv graylog-web
root       371   370  0 13:36 ?        00:00:00 svlogd -tt /var/log/graylog/web
root       493     6  0 13:37 ?        00:00:00 runsv nginx
root       494   493  0 13:37 ?        00:00:00 svlogd -tt /var/log/graylog/nginx
graylog    967   370  2 13:37 ?        00:00:16 /opt/graylog/embedded/jre/bin/java -Xms1024m -Xmx1024m -XX:ReservedCodeCache
root      1037   493  0 13:37 ?        00:00:00 nginx: master process /opt/graylog/embedded/sbin/nginx -c /opt/graylog/conf/
nobody    1038  1037  0 13:37 ?        00:00:00 nginx: worker process
root      1115     1  0 13:37 ?        00:00:00 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 103:106
root      1117     1  0 13:37 ?        00:00:00 tail -F /var/log/graylog/server/current
graylog  10487   327 99 13:46 ?        00:00:36 /opt/graylog/embedded/jre/bin/java -Xms1g -Xmx1g -XX:NewRatio=1 -server -XX:
root     10868     0  1 13:46 ?        00:00:00 bash
root     10899 10868  0 13:46 ?        00:00:00 ps -ef

Open ports in the container:

root@44ecbb92fd9a:/# ss -ltpn
State      Recv-Q Send-Q                              Local Address:Port                                Peer Address:Port
LISTEN     0      128                                             *:80                                             *:*      users:(("nginx",1037,6))
LISTEN     0      128                                     127.0.0.1:7001                                           *:*
LISTEN     0      128                                             *:443                                            *:*      users:(("nginx",1037,7))
LISTEN     0      128                                             *:27017                                          *:*
LISTEN     0      128                                     127.0.0.1:2380                                           *:*
LISTEN     0      128                                            :::4001                                          :::*
LISTEN     0      50                                             :::9000                                          :::*
LISTEN     0      128                                            :::2379                                          :::*

Logs:

2015-08-15_13:42:37.58959 INFO  [node] [graylog2-server] started
2015-08-15_13:42:42.11245 WARN  [jvm] [graylog2-server] [gc][young][6][2] duration [1.5s], collections [1]/[2.4s], total [1.5s]/[2.7s], memory [474.6mb]->[100.5mb]/[972.8mb], all_pools {[young] [396.9mb]->[12.2mb]/[409.6mb]}{[survivor] [51.1mb]->[29.9mb]/[51.1mb]}{[old] [26.4mb]->[63.1mb]/[512mb]}
2015-08-15_13:42:42.59144 INFO  [IndexerSetupService] Checking Elasticsearch HTTP API at http://127.0.0.1:9200/
2015-08-15_13:42:42.60170 ERROR [IndexerSetupService] Could not connect to Elasticsearch.
2015-08-15_13:42:42.60173 java.net.ConnectException: Connection refused
2015-08-15_13:42:42.60174       at java.net.PlainSocketImpl.socketConnect(Native Method)
2015-08-15_13:42:42.60174       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
2015-08-15_13:42:42.60174       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
2015-08-15_13:42:42.60175       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
2015-08-15_13:42:42.60176       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
2015-08-15_13:42:42.60176       at java.net.Socket.connect(Socket.java:589)
2015-08-15_13:42:42.60176       at com.squareup.okhttp.internal.Platform.connectSocket(Platform.java:100)
2015-08-15_13:42:42.60177       at com.squareup.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
2015-08-15_13:42:42.60177       at com.squareup.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
2015-08-15_13:42:42.60178       at com.squareup.okhttp.Connection.connect(Connection.java:152)
2015-08-15_13:42:42.60178       at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:185)
2015-08-15_13:42:42.60178       at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
2015-08-15_13:42:42.60179       at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
2015-08-15_13:42:42.60180       at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
2015-08-15_13:42:42.60180       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
2015-08-15_13:42:42.60181       at com.squareup.okhttp.Call.getResponse(Call.java:273)
2015-08-15_13:42:42.60183       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
2015-08-15_13:42:42.60183       at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
2015-08-15_13:42:42.60184       at com.squareup.okhttp.Call.execute(Call.java:81)
2015-08-15_13:42:42.60184       at org.graylog2.initializers.IndexerSetupService.startUp(IndexerSetupService.java:158)
2015-08-15_13:42:42.60184       at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
2015-08-15_13:42:42.60185       at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
2015-08-15_13:42:42.60185       at java.lang.Thread.run(Thread.java:745)
2015-08-15_13:42:42.60306 ERROR [UI]
2015-08-15_13:42:42.60307
2015-08-15_13:42:42.60308 ################################################################################
2015-08-15_13:42:42.60308
2015-08-15_13:42:42.60309 ERROR: Could not successfully connect to Elasticsearch, if you use multicast check that it is working in your network and that Elasticsearch is running properly and is reachable. Also check that the cluster.name setting is correct.
2015-08-15_13:42:42.60313
2015-08-15_13:42:42.60314 Need help?
2015-08-15_13:42:42.60314
2015-08-15_13:42:42.60314 * Official documentation: http://docs.graylog.org/
2015-08-15_13:42:42.60315 * Community support: https://www.graylog.org/community-support/
2015-08-15_13:42:42.60315 * Commercial support: https://www.graylog.com/support/
2015-08-15_13:42:42.60315
2015-08-15_13:42:42.60316 But we also got some specific help pages that might help you in this case:
2015-08-15_13:42:42.60316
2015-08-15_13:42:42.60317 * http://docs.graylog.org/en/1.0/pages/configuring_es.html
2015-08-15_13:42:42.60317
2015-08-15_13:42:42.60317 Terminating. :(
2015-08-15_13:42:42.60318

**Comment by joschi** [comment]
@leonty Please ensure that there's enough memory available for the Graylog All-in-one container. We recommend 4GB of memory.

For general questions around Graylog, please use [our mailing list](https://groups.google.com/forum/#!forum/graylog2) or our [IRC channel #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog).

**Comment by onmomo** [comment]
@joschi thanks for that hint!
